### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by PatchouliHina**

### CODE REVIEW

**Comment by Mordenkainen** [comment]
I would feel more comfortable if someone could proofread this before putting it in the code. I will reach out and see if I can find someone. Thank you for the update in any case, we'll see about getting it in!

**Comment by 3TUSK** [comment]
tile.techno:reconstructorBlock.name=质再现器

**Comment by Mordenkainen** [comment]
PR shows no +- lines because Github sees the file as Binary. I'm not sure why this is the case.

For line 199, I believe it should indeed be "Powered Magic" (your first suggestion)

@PatchouliHina - Do you agree with these suggestions? If so, can you make the updates, and then I will take the pull request?

**Comment by 3TUSK** [comment]
You're very welcome. But it's still a just rough look... I am probably going to double check it today

**Comment by PatchouliHina** [comment]
OK，I'll do some update. Thanks.

**Comment by PatchouliHina** [comment]
About the "Energized Magic", it is just a bellow. I think it should be "镀锌奥术风箱".
@3TUSK

**Comment by Mordenkainen** [comment]
Also, I think that it is fine if you change the title for the Bellows. But many of the names are not literal, and do not actually list the name of the item. This is the case for the bellows, it is sort of intended as a joke.

**Comment by Mordenkainen** [comment]
Also, after some looking it appears that the "official" translation of "Aspect" for Thaumcraft is 要素

It appears that your translation of line 71 contains this, so ignore my comments for that line! Sorry about that!

**Comment by Mordenkainen** [comment]
Thanks for the update!

I will include it in the build tonight!

@3TUSK - If you have other suggestions for anything you see, either post a comment on this pull request (it will be in the "closed" section), open an issue with your suggested changes, or open a new pull request with the updates. Of course opening a pull request is the most preferred.

Again, thank you both for helping to improve the mod!

**Comment by 3TUSK** [comment]
As long as I find something wrong, I will make new pr. :)

**Pull request merged**
